# Generated by Django 4.0.3 on 2022-03-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(choices=[('LC', 'Licenciatura en Contaduría'), ('LA', 'Licenciatura en Administración'), ('IBM', 'Ingeniería Biomédica'), ('IBQ', 'Ingeniería Bioquímica'), ('IEO', 'Ingeniería Electrónica'), ('IEA', 'Ingeniería Eléctrica'), ('II', 'Ingeniería Industrial'), ('IMOC', 'Ingeniería Mecatrónica'), ('IMEC', 'Ingeniería Mecánica'), ('IGE', 'Ingeniería en Gestión Empresarial'), ('IM', 'Ingeniería en Materiales'), ('ISC', 'Ingeniería en Sistemas Computacionales'), ('ITIC', 'Ingeniería en Tecnologías de la Información y Comunicaciones'), ('MIA', 'Maestría en Ingeniería Administrativa'), ('MSC', 'Maestría en Sistemas Computacionales'), ('MCI', 'Maestría en Ciencias en Ingeniería Electrónica'), ('MCIE', 'Maestría en Ciencias en Ingeniería Eléctrica'), ('MC', 'Maestría en Ciencias en Metalurgia'), ('DCI', 'Doctorado en Ciencias de la Ingeniería'), ('DC', 'Doctorado en Ciencias en Ingeniería Eléctrica')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('no_de_ficha', models.PositiveIntegerField()),
                ('no_de_control', models.CharField(max_length=8)),
                ('escuela_de_procedencia', models.CharField(max_length=255)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('localidad_de_origen', models.CharField(max_length=255)),
                ('municipio_de_origen', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.PositiveSmallIntegerField()),
                ('calificacion_del_examen_de_ingreso', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
